worker_processes: auto
worker_connections: 2048
client_max_body_size: 512M
port_list:
    - { port: 80/tcp, state: enabled }
    - { port: 443/tcp, state: enabled }
service_list:
    - { service: https , state: enabled }
    - { service: http , state: enabled }
